#' Upload an Env-Data request for Annotation
#' 
#' @param csv.file Location and name of \code{.csv} file to annotate, either a MoveBank track or file generated by \code{\link{createEnvDataGrid}}
#' @param xml.file Location and name of \code{.xml} file that contains the request instructions - almost certainly generated by \code{\link{createEnvDataRequest}}
#' @param {login,pw} login and password for EnvData (NOT the same as MoveBank login and password)
#' @param link.file name of link to access status and final annotated data
#' 
#' @details The function will fill out the data annotation form on the EnvData annotation tool at \link{http://www.bioinfo.mpg.de/orn-gateway/services2.jsp}.  It will also create a link to the status report of the annotation request, and (if the user uses chrome, will automatically open that page).   
#' 
#' @example ./examples/EnvDataExample.r
#' 
uploadEnvDataRequest <- function(csv.file, xml.file, login, pw, link.file = "annotation_status_link.url"){
  
  CSV_upload <- fileUpload(filename = csv.file, contentType="text/plain")
  XML_upload <- fileUpload(filename = xml.file, contentType="text/xml")
  h <- basicHeaderGatherer()
  b <- basicHeaderGatherer()
  
  postForm('http://www.bioinfo.mpg.de/orn-gateway/request-annotation-xml-2.jsp', 
           request = XML_upload, tracks = CSV_upload, 
           .params = list(login = login, password = pw), 
           .opts = curlOptions(headerfunction = h$update, writefunction = b$update, verbose = TRUE))
  
  url <- h$value()['Location']
  cat("[InternetShortcut]\n URL=",h$value()['Location'], file = link.file)
  try(shell(paste("chrome", url)))
  return(h)
}



